### ISSUE TITLE
won't compile under ubuntu 16.04

### ISSUE THREAD

**Issue by laurentbriet** [rlk/synaspan#1]
synaspan.c: In function ‘drawstar’:
synaspan.c:245:19: warning: ‘A’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             float k = A * expf(-((xx * xx * c * c) / (s * s) / 2.0f +
                   ^
/usr/bin/ld: /tmp/ccZLH2vj.o: undefined reference to symbol 'expf@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by rlk** [comment]
Fixed. Missing initializer and missing math library.
